---
title: "Job Postings"
toc: true
toc-title: "Job Type"
title-block-banner: "../../images/banners/default-banner.png"
listing:
  - id: academic
    contents: academic-jobs.yml
    sort: "date desc"
    date-format: short
    template: job-listing.ejs
  - id: professional
    contents: professional-jobs.yml
    sort: "date desc"
    date-format: short
    template: job-listing.ejs
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(aplsr)     # rowwise_table()
library(htmltools) # div(), tags$*, a(), span()
library(purrr)     # pmap()
```


::: {.column-screen}
::: {.alt-background-blue}

```{r toc}
#| echo: false
#| message: false
#| warning: false

content = rowwise_table(~name, ~icon, ~link,
          "Post a job",
            "send",
              "https://apls.memberclicks.net/job-posting-request#!/",
          "Post a Clinical-forensic Postdoc",
            "clipboard2-pulse",
              "https://docs.google.com/forms/d/e/1FAIpQLSeyn6YEW7-mne6RsT-yzTMN8HNSXQjuHYPP1DtW7gQq11H9eA/viewform",
          "Post a Research Postdoc",
            "clipboard2-data",
              "https://docs.google.com/forms/d/e/1FAIpQLSfF4iosPXi8pDFG46leWvMk70mnu1qxNzxslH5qfp0JxBqL9A/viewform",
          "Academic Positions",
            "mortarboard",
              "#academic-positions",
          "Professional Positions",
            "briefcase",
              "#professional-positions"
)

div(
  div(
    class = "bg-breakout",
    div(
      class = "inner-container",
      div(
        class = "boxed-wrapper",
        div(
          class = "boxed-feature-grid",
          pmap(content, \(name, icon, link) {
            div(
              class = "boxed-feature-grid__item",
              div(
                class = "boxed-feature-grid__icon",
                a(
                  href = link, 
                  class = "boxed-feature-grid__link",
                  `aria-label` = name,
                  tags$i(class = sprintf("bi-%s boxed-feature-grid__i", icon))
                )
              ),
              div(class = "boxed-feature-grid__title", name)
            )
          })
        )
      )
    )
  )
)
```

:::
:::

::: vspace
:::



## {{< fa graduation-cap >}} Academic Positions {#academic-positions}

::: {#academic}
:::

## {{< fa user-tie >}} Professional Positions {#professional-positions}

::: {#professional}
:::
